Repository OpenVoiceOS/ovos-stt-plugin-wav2vec2, pull requests merged in 2024-09, with the labels that each got.

#1 feat:language_support
  README.md
  ovos_stt_plugin_wav2vec/__init__.py
Labels: feature

#3 fix:standardize_lang_codes
  .github/workflows/unit_tests.yml
  README.md
  ovos_stt_plugin_wav2vec/__init__.py
  requirements.txt
Labels: fix

#5 fix: update requirements.txt
  requirements.txt
Labels: ignore-for-release

#6 feat:cuda support
  ovos_stt_plugin_wav2vec/__init__.py
Labels: feature
